/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f_OCP_adapted_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

static const casadi_int casadi_s0[60] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s1[186] = {2, 61, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1};
static const casadi_int casadi_s2[125] = {1, 61, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s3[308] = {4, 61, 0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68, 72, 76, 80, 84, 88, 92, 96, 100, 104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 148, 152, 156, 160, 164, 168, 172, 176, 180, 184, 188, 192, 196, 200, 204, 208, 212, 216, 220, 224, 228, 232, 236, 240, 244, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s4[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s5[364] = {360, 1, 0, 360, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359};

/* f_integration_k:(i0[2],i1[2],i2,i3,i4[4],i5[4],i6,i7,i8)->(o0,o1[6]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[3]? arg[3][0] : 0;
  a1=arg[6]? arg[6][0] : 0;
  a2=arg[1]? arg[1][0] : 0;
  a3=3.1415926535897931e+000;
  a4=(a2-a3);
  a4=(a1*a4);
  a4=(a0+a4);
  a5=arg[7]? arg[7][0] : 0;
  a6=arg[1]? arg[1][1] : 0;
  a7=(a5*a6);
  a4=(a4+a7);
  a4=casadi_sq(a4);
  a7=1.;
  a8=1.6700000000000001e-001;
  a9=1.3888888888888890e-001;
  a10=(a9*a5);
  a10=(a8*a10);
  a11=2.;
  a10=(a10/a11);
  a10=(a7-a10);
  a12=-8.3500000000000005e-002;
  a13=-5.8859999999999999e+001;
  a14=cos(a2);
  a14=(a13*a14);
  a14=(a14+a1);
  a14=(a9*a14);
  a14=(a8*a14);
  a14=(a14/a11);
  a15=(a12*a14);
  a15=(a10+a15);
  a10=(a10/a15);
  a16=arg[4]? arg[4][3] : 0;
  a17=(a12*a16);
  a18=arg[4]? arg[4][2] : 0;
  a17=(a17-a18);
  a19=(a12*a17);
  a20=arg[4]? arg[4][1] : 0;
  a21=(a12*a20);
  a22=arg[4]? arg[4][0] : 0;
  a21=(a21-a22);
  a19=(a19-a21);
  a23=(a10*a19);
  a24=8.3500000000000005e-002;
  a24=(a24/a15);
  a25=arg[0]? arg[0][0] : 0;
  a26=cos(a25);
  a26=(a13*a26);
  a26=(a26+a1);
  a26=(a9*a26);
  a26=(a8*a26);
  a26=(a26/a11);
  a22=(a26*a22);
  a9=(a9*a5);
  a9=(a8*a9);
  a9=(a9/a11);
  a9=(a9+a7);
  a20=(a9*a20);
  a22=(a22+a20);
  a18=(a26*a18);
  a16=(a9*a16);
  a18=(a18+a16);
  a12=(a12*a18);
  a12=(a22-a12);
  a16=(a24*a12);
  a23=(a23+a16);
  a16=(a23*a10);
  a22=(a22*a26);
  a18=(a18*a9);
  a22=(a22+a18);
  a18=-2.3194444444444448e-002;
  a20=arg[8]? arg[8][0] : 0;
  a20=(a18*a20);
  a18=(a18*a20);
  a22=(a22+a18);
  a18=(a24*a22);
  a21=(a21*a26);
  a17=(a17*a9);
  a21=(a21+a17);
  a17=(a10*a21);
  a18=(a18-a17);
  a17=(a18*a24);
  a16=(a16+a17);
  a17=(a1*a16);
  a14=(a14/a15);
  a19=(a14*a19);
  a12=(a12/a15);
  a19=(a19+a12);
  a10=(a19*a10);
  a22=(a22/a15);
  a21=(a14*a21);
  a22=(a22-a21);
  a24=(a22*a24);
  a10=(a10+a24);
  a24=(a5*a10);
  a17=(a17+a24);
  a17=(a17*a1);
  a23=(a23*a14);
  a18=(a18/a15);
  a23=(a23+a18);
  a18=(a1*a23);
  a19=(a19*a14);
  a22=(a22/a15);
  a19=(a19+a22);
  a22=(a5*a19);
  a18=(a18+a22);
  a18=(a18*a5);
  a17=(a17+a18);
  a4=(a4+a17);
  if (res[0]!=0) res[0][0]=a4;
  a4=arg[0]? arg[0][1] : 0;
  a17=(a4+a6);
  a17=(a17/a11);
  a17=(a8*a17);
  a17=(a25+a17);
  a17=(a2-a17);
  if (res[1]!=0) res[1][0]=a17;
  a17=sin(a25);
  a17=(a13*a17);
  a18=arg[2]? arg[2][0] : 0;
  a17=(a17+a18);
  a25=(a25-a3);
  a25=(a1*a25);
  a17=(a17+a25);
  a25=(a5*a4);
  a17=(a17+a25);
  a25=7.1999999999999993e+000;
  a17=(a17/a25);
  a18=sin(a2);
  a13=(a13*a18);
  a13=(a13+a0);
  a2=(a2-a3);
  a1=(a1*a2);
  a13=(a13+a1);
  a5=(a5*a6);
  a13=(a13+a5);
  a13=(a13/a25);
  a17=(a17+a13);
  a17=(a17/a11);
  a8=(a8*a17);
  a4=(a4+a8);
  a6=(a6-a4);
  if (res[1]!=0) res[1][1]=a6;
  a6=arg[5]? arg[5][0] : 0;
  a6=(a6-a16);
  if (res[1]!=0) res[1][2]=a6;
  a6=arg[5]? arg[5][1] : 0;
  a6=(a6-a10);
  if (res[1]!=0) res[1][3]=a6;
  a6=arg[5]? arg[5][2] : 0;
  a6=(a6-a23);
  if (res[1]!=0) res[1][4]=a6;
  a6=arg[5]? arg[5][3] : 0;
  a6=(a6-a19);
  if (res[1]!=0) res[1][5]=a6;
  return 0;
}

/* map60_f_integration_k:(i0[2x60],i1[2x60],i2[1x60],i3[1x60],i4[4x60],i5[4x60],i6[1x60],i7[1x60],i8[1x60])->(o0[1x60],o1[6x60]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real* *res1;
  const casadi_real* *arg1;
  arg1 = arg+9;
  for (i=0; i<9; ++i) arg1[i]=arg[i];
  res1 = res+2;
  for (i=0; i<2; ++i) res1[i]=res[i];
  for (i=0; i<60; ++i) {
    if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
    if (arg1[0]) arg1[0]+=2;
    if (arg1[1]) arg1[1]+=2;
    if (arg1[2]) arg1[2]+=1;
    if (arg1[3]) arg1[3]+=1;
    if (arg1[4]) arg1[4]+=4;
    if (arg1[5]) arg1[5]+=4;
    if (arg1[6]) arg1[6]+=1;
    if (arg1[7]) arg1[7]+=1;
    if (arg1[8]) arg1[8]+=1;
    if (res1[0]) res1[0]+=1;
    if (res1[1]) res1[1]+=6;
  }
  return 0;
}

/* f_OCP_adapted:(i0[2x61],i1[1x61],i2[4x61],i3,i4)->(o0,o1[360]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+2, *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real **arg1=arg+5;
  casadi_real w0, *w1=w+28, *w2=w+150, *w3=w+270, *w4=w+390, *w5=w+451, *w6=w+511, *w7=w+571, *w8=w+815, *w9=w+1055, w10, *w11=w+1296, *w12=w+1356, *w13=w+1416, *w14=w+1476, *w15=w+1536;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 122, w1);
  /* #2: @2 = @1[:120] */
  for (rr=w2, ss=w1+0; ss!=w1+120; ss+=1) *rr++ = *ss;
  /* #3: @3 = @1[2:122] */
  for (rr=w3, ss=w1+2; ss!=w1+122; ss+=1) *rr++ = *ss;
  /* #4: @4 = input[1][0] */
  casadi_copy(arg[1], 61, w4);
  /* #5: @5 = @4[:60] */
  for (rr=w5, ss=w4+0; ss!=w4+60; ss+=1) *rr++ = *ss;
  /* #6: @6 = @4[1:61] */
  for (rr=w6, ss=w4+1; ss!=w4+61; ss+=1) *rr++ = *ss;
  /* #7: @7 = input[2][0] */
  casadi_copy(arg[2], 244, w7);
  /* #8: @8 = @7[:240] */
  for (rr=w8, ss=w7+0; ss!=w7+240; ss+=1) *rr++ = *ss;
  /* #9: @9 = @7[4:244] */
  for (rr=w9, ss=w7+4; ss!=w7+244; ss+=1) *rr++ = *ss;
  /* #10: @10 = input[3][0] */
  w10 = arg[3] ? arg[3][0] : 0;
  /* #11: @11 = @10[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s0, rr=w11, ss=(&w10); cii!=casadi_s0+60; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #12: @10 = input[4][0] */
  w10 = arg[4] ? arg[4][0] : 0;
  /* #13: @12 = @10[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] */
  for (cii=casadi_s0, rr=w12, ss=(&w10); cii!=casadi_s0+60; ++cii) *rr++ = *cii>=0 ? ss[*cii] : 0;
  /* #14: @13 = all_0.01(1x60) */
  casadi_fill(w13, 60, 1.0000000000000000e-002);
  /* #15: {@14, @15} = map60_f_integration_k(@2, @3, @5, @6, @8, @9, @11, @12, @13) */
  arg1[0]=w2;
  arg1[1]=w3;
  arg1[2]=w5;
  arg1[3]=w6;
  arg1[4]=w8;
  arg1[5]=w9;
  arg1[6]=w11;
  arg1[7]=w12;
  arg1[8]=w13;
  res1[0]=w14;
  res1[1]=w15;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #16: @5 = ones(60x1) */
  casadi_fill(w5, 60, 1.);
  /* #17: @0 = mac(@14,@5,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w14+j, tt=w5+i*60; k<60; ++k) *rr += ss[k*1]**tt++;
  /* #18: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #19: output[1][0] = @15 */
  casadi_copy(w15, 360, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int f_OCP_adapted(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f_OCP_adapted_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f_OCP_adapted_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_OCP_adapted_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f_OCP_adapted_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_OCP_adapted_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f_OCP_adapted_incref(void) {
}

CASADI_SYMBOL_EXPORT void f_OCP_adapted_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f_OCP_adapted_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int f_OCP_adapted_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real f_OCP_adapted_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_OCP_adapted_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_OCP_adapted_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_OCP_adapted_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s3;
    case 3: return casadi_s4;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_OCP_adapted_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f_OCP_adapted_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 23;
  if (sz_res) *sz_res = 6;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 1896;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
